// Code generated by goctl. DO NOT EDIT.
// Source: asset.proto

package server

import (
	"context"

	register2 "grpc-common/ucenter/types/register"
	"ucenter/internal/logic/register"
	"ucenter/internal/svc"
)

type RegisterServer struct {
	svcCtx *svc.ServiceContext
	register2.UnimplementedRegisterServer
}

func NewRegisterServer(svcCtx *svc.ServiceContext) *RegisterServer {
	return &RegisterServer{
		svcCtx: svcCtx,
	}
}

func (s *RegisterServer) RegisterByPhone(ctx context.Context, in *register2.RegReq) (*register2.RegRes, error) {
	l := registerlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.RegisterByPhone(in)
}
func (s *RegisterServer) SendCode(ctx context.Context, in *register2.CodeReq) (*register2.NoRes, error) {
	l := registerlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}