// Code generated by goctl. DO NOT EDIT.
// Source: asset.proto

package client

import (
	"context"
	"grpc-common/market/types/rate"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (

	RegReq     = rate.RateReq
	RegRes     = rate.RateRes

	ExchangeRate interface {
		UsdRate(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error)
	}

	defaultExchangeRate struct {
		cli zrpc.Client
	}
)

func NewExchangeRate(cli zrpc.Client) ExchangeRate {
	return &defaultExchangeRate{
		cli: cli,
	}
}

func (m *defaultExchangeRate) UsdRate(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error) {
	client := rate.NewExchangeRateClient(m.cli.Conn())
	return client.UsdRate(ctx, in, opts...)
}

